# Generated by Django 4.2 on 2023-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_transactions_ben_acct"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
