# Generated by Django 4.2 on 2023-04-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_transactions_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="interDetail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.internationaldetails",
            ),
        ),
    ]
