# Generated by Django 4.2 on 2023-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_transactions_interdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="internationaldetails",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
