# Generated by Django 4.2 on 2023-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_internationaldetails_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("DECLINED", "DECLINED"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
    ]
